# data
data:
  instruct_data: "../QA_Dataset/q_a_pairs_mistral_train.jsonl"  # Fill
  data: ""  # Optionally fill with pretraining data 
  eval_instruct_data: "../QA_Dataset/q_a_pairs_mistral_test.jsonl"  # Optionally fill

# model
model_id_or_path: "../mistral_model/finetuning_model"  # Change to downloaded path
lora:
  rank: 64

# optim
seq_len: 32768
batch_size: 1
max_steps: 300
optim:
  lr: 6.e-5
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
no_eval: False
ckpt_freq: 100

save_adapters: True  # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model

run_dir: "../finetuning_result"  # Fill

